
[package]
name = "dkey"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
blake3 = "1.8.2"
password-hash = "0.5.0"
rpassword = "7.3"
zeroize = "1.5"
rand = "0.8"
rand_chacha = "0.3"
base64 = "0.21"
clap = { version = "4.1.14", features = ["derive"] }
