[package]
name = "aes-cbc"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.7"                     # ✅ uses cipher 0.3
block-modes = "0.8.1"           # ✅ uses cipher 0.3
block-padding = "0.3"
rand = "0.8"
anyhow = "1.0"
