[package]
name = "file_crypto_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10"
aead = "0.5.2"
clap = { version = "4.2", features = ["derive"] }
pbkdf2 = "0.12"
sha2 = "0.10"
anyhow = "1.0"
base64ct = "1.8.0"
subtle = "2.6.1"
rand = "0.8"
