[package]
name = "securepass"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm-siv = "0.11"
argon2 = "0.5"
rand = "0.8"
rpassword = "7.2"
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
zeroize = "1.6"
