[package]
name = "xor"
version = "0.1.0"
edition = "2024"


[dependencies]
atomic-write-file = "0.2.3"
sys-info = "0.9.1"
zeroize = "1.8.1"
chrono = "0.4"              # ⏱️ for timestamped error logs
sha2 = "0.10"