[package]
name = "threefish_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
threefish = "0.5.2"
rand = "0.9.1"
zeroize = "1.8.1"
anyhow   = "1.0.98"
hmac = "0.12.1"
sha2 = "0.10.0"
tempfile = "3.20.0"
argon2 = "0.5.3"
rpassword = "7.4.0"